linux用configureの改善。

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -129,7 +129,6 @@ options:
   --extra-cxxflags=XCFLAGS add XCFLAGS to CFLAGS
   --extra-ldflags=XLDFLAGS add XLDFLAGS to LDFLAGS
 
-  --disable-libva          disable libva support [auto]
   --disable-vapoursynth    disable vapoursynth support [auto]
   --disable-libass         disable libass support [auto]
   --disable-dtl            disable dtl support [auto]
@@ -170,9 +169,6 @@ for opt; do
             ;;
         --enable-debug)
             ENABLE_DEBUG=1
-            ;;
-        --disable-libva)
-            LIBVA_SUPPORT=0
             ;;
         --disable-vapoursynth)
             ENABLE_VAPOURSYNTH=0
@@ -312,65 +308,14 @@ else
     LDFLAGS="$LDFLAGS -Wl,-s"
 fi
 
-printf "checking for libmfx..."
-if cxx_check "${CXXFLAGS} ${LDFLAGS} -lmfx" ; then
-    LDFLAGS="$LDFLAGS -lmfx"
-    echo "yes"
-else
-    LIBVA_SUPPORT=0
-    echo "no"
+printf "checking for pkg-config..."
+export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$PREFIX/lib/pkgconfig
+which $PKGCONFIG 2>/dev/null 1>/dev/null
+if [ $? -ne 0 ]; then
+    echo "${PKGCONFIG} does not exist."
+    USE_PKGCONFIG=0
 fi
-
-printf "checking for libva_drm..."
-if [ $LIBVA_SUPPORT -ne 0 ]; then
-    if cxx_check "${CXXFLAGS} ${LDFLAGS} -lva-drm -ldrm -lva" "" "va/va_drm.h" "" ; then
-        LDFLAGS="$LDFLAGS -lva-drm"
-        CXXFLAGS="$CXXFLAGS -DLIBVA_DRM_SUPPORT"
-        echo "yes"
-    else
-        LIBVA_DRM_SUPPORT=0
-        echo "no"
-    fi
-fi
-
-printf "checking for libva_x11..."
-if [ $LIBVA_SUPPORT -ne 0 ]; then
-    if cxx_check "${CXXFLAGS} ${LDFLAGS} -lva-x11 -lva" "" "va/va_x11.h" "" ; then
-        LDFLAGS="$LDFLAGS -lva-x11"
-        CXXFLAGS="$CXXFLAGS -DLIBVA_X11_SUPPORT"
-        echo "yes"
-    else
-        LIBVA_X11_SUPPORT=0
-        echo "no"
-    fi
-fi
-
-printf "checking for libva..."
-if [ $LIBVA_SUPPORT -ne 0 ]; then
-    if cxx_check "${CXXFLAGS} ${LDFLAGS} -lva" "" "va/va.h" "" ; then
-        LDFLAGS="$LDFLAGS -lva"
-        CXXFLAGS="$CXXFLAGS -DLIBVA_SUPPORT"
-        echo "yes"
-    else
-        LIBVA_SUPPORT=0
-        echo "no"
-    fi
-fi
-
-printf "checking for drm..."
-if [ $LIBVA_SUPPORT -ne 0 ]; then
-    if cxx_check "${CXXFLAGS} ${LDFLAGS} -ldrm" "" "drm.h" "" ; then
-        LDFLAGS="$LDFLAGS -ldrm"
-        echo "yes"
-    elif cxx_check "${CXXFLAGS} -I/usr/include/libdrm ${LDFLAGS} -ldrm" "" "drm.h" "" ; then
-        LDFLAGS="$LDFLAGS -ldrm"
-        CXXFLAGS="$CXXFLAGS -I/usr/include/libdrm"
-        echo "yes"
-    else
-        LIBVA_SUPPORT=0
-        echo "no"
-    fi
-fi
+echo "OK"
 
 if [ -n $EXTRACXXFLAGS ]; then
     printf "checking --extra-cflags..."
@@ -390,14 +335,104 @@ if [ -n $EXTRALDFLAGS ]; then
     echo "OK"
 fi
 
-printf "checking for pkg-config..."
-export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$PREFIX/lib/pkgconfig
-which $PKGCONFIG 2>/dev/null 1>/dev/null
-if [ $? -ne 0 ]; then
-    echo "${PKGCONFIG} does not exist."
-    USE_PKGCONFIG=0
+printf "checking for libva-drm..."
+LIBVA_DRM_LIBS="-lva-drm -lva"
+LIBVA_DRM_CFLAGS=
+LIBVA_DRM_SUPPORT=0
+if ! ${PKGCONFIG} --exists libva-drm ; then
+    echo "libva-drm could not be detected by ${PKGCONFIG}. [ PKG_CONFIG_PATH=${PKG_CONFIG_PATH} ]"
+else
+    LIBVA_DRM_LIBS=`${PKGCONFIG} --libs libva-drm`
+    LIBVA_DRM_CFLAGS=`${PKGCONFIG} --cflags libva-drm`
 fi
-echo "OK"
+if cxx_check "${CXXFLAGS} ${EXTRACXXFLAGS} ${LIBVA_DRM_CFLAGS} ${LDFLAGS} ${EXTRALDFLAGS} ${LIBVA_DRM_LIBS}" "va/va_drm.h" "" "vaGetDisplayDRM(0);" ; then
+    LDFLAGS="${LDFLAGS} ${LIBVA_DRM_LIBS}"
+    CXXFLAGS="${CXXFLAGS} ${LIBVA_DRM_CFLAGS} -DLIBVA_DRM_SUPPORT"
+    LIBVA_DRM_SUPPORT=1
+    echo "yes"
+else
+    echo "no"
+fi
+
+printf "checking for libva_x11..."
+LIBVA_X11_LIBS="-lva-x11 -lva"
+LIBVA_X11_CFLAGS=
+LIBVA_X11_SUPPORT=0
+if ! ${PKGCONFIG} --exists libva-x11 ; then
+    echo "libva-x11 could not be detected by ${PKGCONFIG}. [ PKG_CONFIG_PATH=${PKG_CONFIG_PATH} ]"
+else
+    LIBVA_X11_LIBS=`${PKGCONFIG} --libs libva-x11`
+    LIBVA_X11_CFLAGS=`${PKGCONFIG} --cflags libva-x11`
+fi
+if cxx_check "${CXXFLAGS} ${EXTRACXXFLAGS} ${LIBVA_X11_CFLAGS} ${LDFLAGS} ${EXTRALDFLAGS} ${LIBVA_X11_LIBS}" "va/va_x11.h" "" "vaGetDisplay(0);" ; then
+    LDFLAGS="${LDFLAGS} ${LIBVA_X11_LIBS}"
+    CXXFLAGS="${CXXFLAGS} ${LIBVA_X11_CFLAGS} -DLIBVA_X11_SUPPORT"
+    LIBVA_X11_SUPPORT=1
+    echo "yes"
+else
+    echo "no"
+fi
+
+printf "checking for libva..."
+LIBVA_SUPPORT=0
+if [ $LIBVA_DRM_SUPPORT -ne 0 -o $LIBVA_X11_SUPPORT -ne 0 ]; then
+    LIBVA_SUPPORT=1
+    CXXFLAGS="${CXXFLAGS} -DLIBVA_SUPPORT"
+    echo "yes"
+else
+    if ! ${PKGCONFIG} --exists libva ; then
+        echo "libva could not be detected by ${PKGCONFIG}. [ PKG_CONFIG_PATH=${PKG_CONFIG_PATH} ]"
+    else
+        LIBVA_LIBS=`${PKGCONFIG} --libs libva`
+        LIBVA_CFLAGS=`${PKGCONFIG} --cflags libva`
+    fi
+    if cxx_check "${CXXFLAGS} ${EXTRACXXFLAGS} ${LIBVA_CFLAGS} ${LDFLAGS} ${EXTRALDFLAGS} ${LIBVA_LIBS}" "va/va.h" "" "vaDestroyBuffer(0,0);" ; then
+        LDFLAGS="${LDFLAGS} ${LIBVA_LIBS}"
+        CXXFLAGS="${CXXFLAGS} ${LIBVA_CFLAGS} -DLIBVA_SUPPORT"
+        LIBVA_SUPPORT=1
+        echo "yes"
+    else
+        echo "libva not installed." 
+        exit 1
+    fi
+fi
+
+printf "checking for drm..."
+LIBDRM_LIBS="-ldrm"
+LIBDRM_CFLAGS=
+LIBDRM_SUPPORT=0
+if ! ${PKGCONFIG} --exists libdrm ; then
+    echo "libva-x11 could not be detected by ${PKGCONFIG}. [ PKG_CONFIG_PATH=${PKG_CONFIG_PATH} ]"
+else
+    LIBDRM_LIBS=`${PKGCONFIG} --libs libdrm`
+    LIBDRM_CFLAGS=`${PKGCONFIG} --cflags libdrm`
+fi
+if cxx_check "${CXXFLAGS} ${EXTRACXXFLAGS} ${LIBDRM_CFLAGS} ${LDFLAGS} ${EXTRALDFLAGS} ${LIBDRM_LIBS}" "xf86drm.h" "" "drmOpen(0,0);" ; then
+    LDFLAGS="${LDFLAGS} ${LIBDRM_LIBS}"
+    CXXFLAGS="${CXXFLAGS} ${LIBDRM_CFLAGS}"
+    LIBDRM_SUPPORT=1
+    echo "yes"
+else
+    echo "no"
+fi
+
+printf "checking for libmfx..."
+LIBMFX_LIBS="-lmfx"
+LIBMFX_CFLAGS=
+if ! ${PKGCONFIG} --exists libmfx ; then
+    echo "libmfx could not be detected by ${PKGCONFIG}. [ PKG_CONFIG_PATH=${PKG_CONFIG_PATH} ]"
+else
+    LIBMFX_LIBS=`${PKGCONFIG} --libs libmfx`
+    LIBMFX_CFLAGS=`${PKGCONFIG} --cflags libmfx`
+fi
+if cxx_check "${CXXFLAGS} ${EXTRACXXFLAGS} ${LIBMFX_CFLAGS} ${LDFLAGS} ${EXTRALDFLAGS} ${LIBMFX_LIBS}" "" "mfxsession.h" "MFXInit(0,0,0);" ; then
+    LDFLAGS="${LDFLAGS} ${LIBMFX_LIBS}"
+    CXXFLAGS="${CXXFLAGS} ${LIBMFX_CFLAGS}"
+    echo "yes"
+else
+    echo "libmfx not installed." 
+    exit 1
+fi
 
 if [ $ENABLE_AVSW_READER -ne 0 ]; then
     if [ $USE_PKGCONFIG -ne 0 ]; then
